# Generated by Django 3.0.1 on 2020-08-15 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fullcalendar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
