# Generated by Django 3.0.1 on 2020-04-24 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fullcalendar', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='name',
            new_name='title',
        ),
    ]
