# Generated by Django 3.0.1 on 2020-04-27 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fullcalendar', '0002_auto_20200424_1245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='title',
            new_name='event_name',
        ),
    ]
