# Generated by Django 3.0.1 on 2020-04-27 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fullcalendar', '0003_auto_20200427_0524'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='event_name',
            new_name='title',
        ),
    ]
